- name: "NOTSCORED | 4.1.1.1 | PATCH | Ensure audit log storage size is configured"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file"
      line: "max_log_file = 10"
      state: present
  when: cis_4_1_1_1
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.1.1

- name: "SCORED | 4.1.1.2 | PATCH | Ensure system is disabled when audit logs are full"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^admin_space_left_action"
      line: "admin_space_left_action = halt"
      state: present
  when: cis_4_1_1_2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.1.2

- name: "SCORED | 4.1.1.3 | PATCH | Ensure audit logs are not automatically deleted"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file_action"
      line: "max_log_file_action = keep_logs"
      state: present
  when: cis_4_1_1_3
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.1.3

- name: "SCORED | 4.1.2 | PATCH | Ensure auditd service is enabled"
  service:
      name: auditd
      state: started
      enabled: yes
  when: rhel7cis_skip_for_travis == false and cis_4_1_2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.2

- name: "SCORED | 4.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
      replace: '\1"\2 audit=1"'
      follow: yes
  ignore_errors: yes
  when: cis_4_1_3
  notify: generate new grub config
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.3

- name: "SCORED | 4.1.4 | PATCH | Ensure events that modify date and time information are collected"
  command: /bin/true
  when: cis_4_1_4
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.4

- name: "SCORED | 4.1.5 | PATCH | Ensure events that modify user/group information are collected"
  command: /bin/true
  when: cis_4_1_5
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.5

- name: "SCORED | 4.1.6 | PATCH | Ensure events that modify the system's network environment are collected"
  command: /bin/true
  when: cis_4_1_6
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.6

- name: "SCORED | 4.1.7 | PATCH | Ensure events that modify the system's Mandatory Access Controls are collected"
  command: /bin/true
  when: cis_4_1_7
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.7


- name: "SCORED | 4.1.8 | PATCH | Ensure login and logout events are collected"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: "-w /var/log/tallylog -p wa -k account-access"
      state: present
  when: cis_4_1_8
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.8

- name: "SCORED | 4.1.8 | PATCH | Ensure login and logout events are collected"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: "-w /var/run/faillock -p wa -k  account-access"
      state: present
  when: cis_4_1_8
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.8

- name: "SCORED | 4.1.8 | PATCH | Ensure login and logout events are collected"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: "-w /var/log/lastlog -p wa -k  account-access"
      state: present
  when: cis_4_1_8
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.8


- name: "SCORED | 4.1.9 | PATCH | Ensure session initiation information is collected"
  command: /bin/true
  when: cis_4_1_9
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.9

- name: "SCORED | 4.1.10 | PATCH | Ensure discretionary access control permission modification events are collected"
  command: /bin/true
  when: cis_4_1_10
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.10

- name: "SCORED | 4.1.11 | PATCH | Ensure unsuccessful unauthorized file access attempts are collected"
  command: /bin/true
  when: cis_4_1_11
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.11

- name: "SCORED | 4.1.12 | PATCH | Ensure use of privileged commands is collected"
  command: /bin/true
  when: cis_4_1_12
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.12

- name: "SCORED | 4.1.13 | PATCH | Ensure successful file system mounts are collected"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: "-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
      state: present
  when: cis_4_1_13
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.13

- name: "SCORED | 4.1.13 | PATCH | Ensure successful file system mounts are collected"
  lineinfile:
      dest: /etc/audit/audit.rules
      line: "-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
      state: present
  when: cis_4_1_13
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.13

- name: "SCORED | 4.1.13 | PATCH | Ensure successful file system mounts are collected"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: "-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
      state: present
  when: cis_4_1_13
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.13

- name: "SCORED | 4.1.14 | PATCH | Ensure file deletion events by users are collected"
  command: /bin/true
  when: cis_4_1_14
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.14

- name: "SCORED | 4.1.15 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: "-w /etc/sudoers -p wa -k scope"
      state: present
  when: cis_4_1_15
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.15

- name: "SCORED | 4.1.15 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  lineinfile:
      dest: /etc/audit/audit.rules
      line: "-w /etc/sudoers -p wa -k scope"
      state: present
  when: cis_4_1_15
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.15

- name: "SCORED | 4.1.15 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: "-w /etc/sudoers.d -p wa -k scope"
      state: present
  when: cis_4_1_15
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.15

- name: "SCORED | 4.1.16 | PATCH | Ensure system administrator actions (sudolog) are collected"
  command: /bin/true
  when: cis_4_1_16
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.16

- name: "SCORED | 4.1.17 | PATCH | Ensure kernel module loading and unloading is collected"
  command: /bin/true
  when: cis_4_1_17
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.17

- name: "SCORED | 4.1.18 | PATCH | Ensure the audit configuration is immutable"
  command: /bin/true
  when: cis_4_1_18
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.18

- name: "SCORED | 4.2.1.1 | PATCH | Ensure rsyslog Service is enabled - service install"
  yum:
      name: rsyslog
      state: present
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.1.1

- name: "SCORED | 4.2.1.1 | PATCH | Ensure rsyslog Service is enabled - service start"
  service:
      name: rsyslog
      state: started
      enabled: yes
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.1.1

# - name: "NOTSCORED | 4.2.1.2 | PATCH | Ensure logging is configured"
#   command: /bin/true
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_4.2.1.2

- name: "SCORED | 4.2.1.3 | PATCH | Ensure rsyslog default file permissions configured"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode\s+'
      line: "$FileCreateMode 0640"
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.1.3

- name: "SCORED | 4.2.1.3 | PATCH | Ensure rsyslog default file permissions configured - reload config"
  service:
      name: rsyslog
      state: restarted
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.1.3

# - name: "SCORED | 4.2.1.4 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
#   command: /bin/true
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_4.2.1.4

# - name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
#   command: /bin/true
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_4.2.1.5

# - name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
#   command: /bin/true
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_4.2.1.5

# - name: "SCORED | 4.2.2.1 | PATCH | Ensure syslog-ng service is enabled"
#   command: /bin/true
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_4.2.2.1

# - name: "NOTSCORED | 4.2.2.2 | PATCH | Ensure logging is configured"
#   command: /bin/true
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_4.2.2.2

# - name: "SCORED | 4.2.2.3 | PATCH | Ensure syslog-ng default file permissions configured"
#   command: /bin/true
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_4.2.2.3

# - name: "NOTSCORED | 4.2.2.4 | PATCH | Ensure syslog-ng is configured to send logs to a remote log host"
#   command: /bin/true
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_4.2.2.4

# - name: "NOTSCORED | 4.2.2.5 | PATCH | Ensure remote syslog-ng messages are only accepted on designated log hosts"
#   command: /bin/true
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_4.2.2.5

# - name: "SCORED | 4.2.3 | PATCH | Ensure rsyslog or syslog-ng is installed"
#   command: /bin/true
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_4.2.3

##################### may cause errors on some services #########################

- name: "SCORED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured - patch logrotate config"
  command: sed -i -e 's/create 06\([123567][0-7]\|[0-7][1-7]\)/create 0640/g' /etc/logrotate.conf
  when: cis_4_2_4
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.4

- name: "SCORED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured - patch rhel-dmesg (1/4)"
  copy:
      src: /usr/lib/systemd/rhel-dmesg
      dest: /usr/lib/systemd/rhel-dmesg-cis
      mode: 0755
      remote_src: yes
  when: cis_4_2_4 and ansible_os_family == "RedHat"
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.4

- name: "SCORED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured - patch rhel-dmesg (2/4)"
  lineinfile:
      dest: /usr/lib/systemd/rhel-dmesg-cis
      regexp: '^umask '
      line: "umask 0077"
      insertafter: '^#!'
      state: present
  when: cis_4_2_4 and ansible_os_family == "RedHat"
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.4

- name: "SCORED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured - patch rhel-dmesg (3/4)"
  copy:
      src: /usr/lib/systemd/system/rhel-dmesg.service
      dest: /etc/systemd/system/rhel-dmesg.service
      mode: 0644
      remote_src: yes
  when: cis_4_2_4 and ansible_os_family == "RedHat"
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.4

- name: "SCORED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured - patch rhel-dmesg (4/4)"
  lineinfile:
      dest: /etc/systemd/system/rhel-dmesg.service
      regexp: '^ExecStart='
      line: "ExecStart=/usr/lib/systemd/rhel-dmesg-cis"
      state: present
  when: cis_4_2_4 and ansible_os_family == "RedHat"
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.4

- name: "SCORED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured - fix wtmp permissions"
  lineinfile:
      dest: /lib/tmpfiles.d/var.conf
      regexp: '^f /var/log/wtmp '
      line: "f /var/log/wtmp 0640 root utmp -"
      state: present
  when: cis_4_2_4 and ansible_os_family == "RedHat"
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.4

- name: "SCORED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured"
  command: find /var/log -type f -exec chmod g-wx,o-rwx {} +
  when: cis_4_2_4
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.4

# - name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
#   command: /bin/true
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_4.3
