## -- Install CA APM Java Agent
#
#

- name: create new javaagent folder
  shell: "mkdir -p /var/apphome/{{appid}}_{{appshort}}/{{appid}}_{{appshort}}_javaagent-{{ clonenr }}/"
  when: not ansible_check_mode and STATE == "present"
  tags:
    - caapm
    - javaagent

- name: untar AUDI_Standard_Tomcat_Agent_v1.tar to javaagent folder
  shell: "tar -C /var/apphome/{{appid}}_{{appshort}}/{{appid}}_{{appshort}}_javaagent-{{ clonenr }}/ -xf /tmp/AUDI_Standard_Tomcat_Agent_v1.tar"
  when: not ansible_check_mode and STATE == "present"
  tags:
    - caapm
    - javaagent

- name: change permissions
  file:
    dest: "/var/apphome/{{appid}}_{{appshort}}/{{appid}}_{{appshort}}_javaagent-{{ clonenr }}/"
    owner: "{{ app_runuser }}"
    group: "{{ app_group }}"
    recurse: yes
  when: not ansible_check_mode and STATE == "present"
  tags:
    - caapm
    - javaagent

- name: find correct settings file containing tc_env
  shell: 
    cmd: "egrep -l '^TC_?ENV' {{ tc8_tc_setenvscript }} {{ tc8_tc_startscript }} {{ tc85_tc_setenvscript }} {{ tc85_tc_startscript }}"
  register: tc_env_files
  #when:  STATE == "present"
  ignore_errors: true

- name: install the javaagent
  lineinfile:
    backup: yes
    insertbefore: '^\s*TC_?ENV'
    line: 'export CATALINA_OPTS=${CATALINA_OPTS}" -javaagent:/var/apphome/{{appid}}_{{appshort}}/{{appid}}_{{appshort}}_javaagent-{{ clonenr }}/wily/Agent.jar -Dcom.wily.introscope.agentProfile=/var/apphome/{{appid}}_{{appshort}}/{{appid}}_{{appshort}}_javaagent-{{clonenr}}/wily/core/config/IntroscopeAgent.profile -Dintroscope.agent.agentName={{appidfull}}-{{ clonenr }} -DagentManager.url.1={{ ca_apm_server }}:5001 "'
    path: "{{ item }}"
    state: "{{ STATE }}"
  with_items: 
    - "{{ tc_env_files.stdout_lines }}"
  when: not ansible_check_mode
  ignore_errors: yes
  tags:
    - caapm
    - javaagent

- name: delete Appdynamics prop file to deactivate Appdynamics (re-activate it by running _update_appdynamics_agent.yml playbook)
  shell: 
    cmd: "rm /opt/appdynamics/javaagent/current/conf/{{ appid }}_{{ appshort }}-{{ clonenr }}.prop"
  ignore_errors: yes
  when: not ansible_check_mode and STATE == "present"
  tags:
    - caapm
    - javaagent

## UNINSTALL

- name: remove javaagent folder
  shell: "rm -rf /var/apphome/{{appid}}_{{appshort}}/{{appid}}_{{appshort}}_javaagent-{{ clonenr }}/"
  when: not ansible_check_mode and STATE == "absent"
  tags:
    - caapm
    - javaagent
